<?php

namespace HeroesBundle\Repository;

/**
 * FavoritesHeroesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritesHeroesRepository extends \Doctrine\ORM\EntityRepository
{
}
